In [3]:
import numpy as np

def linear_regression_hypothesis(X, theta):

    h = np.dot(X, theta)
    return h

In [4]:
def compute_cost(X, y, theta):
    m = len(y)
    h = linear_regression_hypothesis(X, theta)
    J = np.sum((h - y) **2)/(2*m)
    return J


In [5]:
def gradient_descent_step(X, y, theta, alpha):
    m = len(y)
    h = linear_regression_hypothesis(X, theta)
    gradient = np.dot(X.T, (h - y)) / m
    theta = theta - alpha * gradient
    return theta

In [6]:
import pandas as pd
import numpy as np


apartments = pd.read_csv("Housing.csv")


X = apartments[["area", "bedrooms", "bathrooms"]]
y = apartments["price"].values.reshape(-1, 1)

X = (X - np.mean(X, axis=0)) / np.std(X, axis=0)
theta = np.zeros((X.shape[1], 1))


def linear_regression_hypothesis(X, theta):
    return np.dot(X, theta)


def compute_cost(X, y, theta):
    m = len(y)
    h = linear_regression_hypothesis(X, theta)
    J = np.sum((h - y) ** 2) / (2 * m)
    return J

# Definicja algorytmu gradientowego spadku
def gradient_descent(X, y, theta, alpha, num_iterations):
    m = len(y)
    J_history = []
    for _ in range(num_iterations):
        h = linear_regression_hypothesis(X, theta)
        gradient = np.dot(X.T, (h - y)) / m
        theta -= alpha * gradient
        J_history.append(compute_cost(X, y, theta))
    return theta, J_history


alpha = 0.01  # Współczynnik uczenia
num_iterations = 1000  # Liczba iteracji

theta_optimal, J_history = gradient_descent(X, y, theta, alpha, num_iterations)

print("Optymalne parametry theta:")
print(f"Współczynnik dla cechy 'area': {theta_optimal[0][0]}")
print(f"Współczynnik dla cechy 'bedrooms': {theta_optimal[1][0]}")
print(f"Współczynnik dla cechy 'bathrooms': {theta_optimal[2][0]}")


Optymalne parametry theta:
Współczynnik dla cechy 'area': 821199.2670986366
Współczynnik dla cechy 'bedrooms': 300296.2856063652
Współczynnik dla cechy 'bathrooms': 695515.9962379065


In [11]:
import numpy as np


X_with_intercept = np.c_[np.ones((X.shape[0], 1)), X]


theta_analytical = np.linalg.inv(X_with_intercept.T.dot(X_with_intercept)).dot(X_with_intercept.T).dot(y)

print("Optymalne parametry theta (rozwiązanie analityczne):")
print(theta_analytical)

Optymalne parametry theta (rozwiązanie analityczne):
[[4766729.24770643]
 [ 821214.14349518]
 [ 299983.57107963]
 [ 695808.52272538]]


In [13]:
# Wyświetlenie wyników
print("Optymalne parametry theta uzyskane przez gradientowy spadek:")
print(theta_optimal)
print("\nOptymalne parametry theta uzyskane analitycznie:")
print(theta_analytical)

Optymalne parametry theta uzyskane przez gradientowy spadek:
[[821199.26709864]
 [300296.28560637]
 [695515.99623791]]

Optymalne parametry theta uzyskane analitycznie:
[[4766729.24770643]
 [ 821214.14349518]
 [ 299983.57107963]
 [ 695808.52272538]]
